const newTests = [
    {   
        'id': 0,
        'subject': 'Физика',
        'topic': 'Квантовая механика',
        'result': '95%',
        'startDate': '01.01.2022',
        'endDate': '15.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 1,
        'subject': 'Химия',
        'topic': 'Органическая химия',
        'result': '88%',
        'startDate': '02.01.2022',
        'endDate': '02.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 2,
        'subject': 'Биология',
        'topic': 'Генетика',
        'result': '92%',
        'startDate': '03.01.2022',
        'endDate': '03.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 3,
        'subject': 'История',
        'topic': 'Древний Рим',
        'result': '85%',
        'startDate': '04.01.2022',
        'endDate': '04.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 4,
        'subject': 'География',
        'topic': 'Климатические зоны',
        'result': '90%',
        'startDate': '05.01.2022',
        'endDate': '05.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 5,
        'subject': 'Литература',
        'topic': 'Русская классика',
        'result': '87%',
        'startDate': '06.01.2022',
        'endDate': '06.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 6,
        'subject': 'Английский язык',
        'topic': 'Грамматика',
        'result': '93%',
        'startDate': '07.01.2022',
        'endDate': '07.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 7,
        'subject': 'Информатика',
        'topic': 'Алгоритмы',
        'result': '96%',
        'startDate': '08.01.2022',
        'endDate': '08.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 8,
        'subject': 'Физкультура',
        'topic': 'Здоровый образ жизни',
        'result': '89%',
        'startDate': '09.01.2022',
        'endDate': '09.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    },
    {
        'id': 9,
        'subject': 'Математика',
        'topic': 'Дифференциальные уравнения',
        'result': '94%',
        'startDate': '10.01.2022',
        'endDate': '10.01.2022',
        'maxTime': '60 minutes',
        'numQuestions': 20,
        'maxPoints': 100,
        'numTries': 1,
        'isAccess': true,
    }
];
export default newTests;